# site settings
title: Lgreco | Î›Greco
google_analytics_id: UA-47897501-1
# url: "http://lgreco.eu"
shareaholic_app_id: 23126307
shareaholic_site_id: bcf4fb9a3f70ecd99f1e09171fcf2fa1

# standard jekyll configuration
exclude:
- Gemfile
- Gemfile.lock
- README.md
- "*.bat"
- CNAME